//
//  ShowDetailInteractor.swift
//  FakeVK
//
//  Created by Admin on 28.01.2020.
//  Copyright (c) 2020 Kanat Kuanyshbek. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailBusinessLogic
{
  func doSomething(request: ShowDetail.Something.Request)
}

protocol ShowDetailDataStore
{
  var name: String { get set }
}

class ShowDetailInteractor: ShowDetailBusinessLogic, ShowDetailDataStore
{
  var presenter: ShowDetailPresentationLogic?
  var worker: ShowDetailWorker?
  var name: String = "4"
  
  // MARK: Do something
  
  func doSomething(request: ShowDetail.Something.Request)
  {
    worker = ShowDetailWorker()
    worker?.doSomeWork()
    
    let response = ShowDetail.Something.Response()
    presenter?.presentSomething(response: response)
    print(name)
  }
}
