//
//  ShowDetailWorker.swift
//  FakeVK
//
//  Created by Admin on 28.01.2020.
//  Copyright (c) 2020 Kanat Kuanyshbek. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ShowDetailWorker
{
  func doSomeWork()
  {
  }
}
