//
//  ShowDetailPresenter.swift
//  FakeVK
//
//  Created by Admin on 28.01.2020.
//  Copyright (c) 2020 Kanat Kuanyshbek. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowDetailPresentationLogic
{
  func presentSomething(response: ShowDetail.Something.Response)
}

class ShowDetailPresenter: ShowDetailPresentationLogic
{
  weak var viewController: ShowDetailDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ShowDetail.Something.Response)
  {
    let viewModel = ShowDetail.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
